verbose: true
types:
  tpr_service_channel: {  }
  tpr_errand_service: {  }
  tpr_ontology_word_details: {  }
  tpr_service:
    '*': '*'
  tpr_unit:
    '*': '*'
  node:
    '*': '*'
  paragraphs_library_item:
    '*': '*'
  taxonomy_term:
    '*': '*'
form_op_lock:
  tpr_service_channel:
    mode: 0
    values: {  }
  tpr_errand_service:
    mode: 0
    values: {  }
  tpr_ontology_word_details:
    mode: 0
    values: {  }
  tpr_service:
    mode: 0
    values: {  }
  tpr_unit:
    mode: 0
    values: {  }
timeout: 7200
